### ISSUE TITLE
Drupal Rate module marked unsupported

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/rate#1]
Today (Jan 26th, 2022) the Drupal Rate module was marked unsupported.

I have [offered to co-maintain the Rate module for Drupal](https://www.drupal.org/project/projectownership/issues/3260733) in the hopes that I can help fix and/or test the solution to the unresolved security issue. 

Once There is a solution that the Drupal security team approves of, both projects should have a matching release. I'm hoping I can help coordinate those releases @robertgarrigos

**Comment by robertgarrigos** [comment]
You are more than welcome, @jenlampton

**Comment by jenlampton** [comment]
The drupal maintainers have created a new release of Rate module, with the security fix: 
https://www.drupal.org/project/rate/releases/7.x-1.8 

We should either cherry-pick in the commits from the Drupal project, or re apply all the patches. Do you have a preference for which way we approach it @robertgarrigos?

**Comment by robertgarrigos** [comment]
No, I do not have a preference. Given I will not be able to do it right now, please, proceed as you prefer. Thanks, @jenlampton

**Comment by robertgarrigos** [comment]
Just reopen this to make sure we catch up with drupal module.

**Comment by robertgarrigos** [comment]
> The drupal maintainers have created a new release of Rate module, with the security fix: https://www.drupal.org/project/rate/releases/7.x-1.8
> 
> We should either cherry-pick in the commits from the Drupal project, or re apply all the patches. Do you have a preference for which way we approach it @robertgarrigos?

@jenlampton I have just checked that everything new from 7.x-1.8 was in the backdrop version. If you agree, I would make a release with the 1.x-1.8.0 tag and a note on the README to make it clear. Is that ok?

**Comment by robertgarrigos** [comment]
Just done a new release to pick up with the Drupal version number
